<?php

use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function drupal_path_guard_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.drupal_path_guard':
            $text = file_get_contents(__DIR__ . '/README.txt');
            if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
                return '<pre>' . Html::escape($text) . '</pre>';
            } else {
                // Use the Markdown filter to render the README.
                $filter_manager = \Drupal::service('plugin.manager.filter');
                $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
                $config = ['settings' => $settings];
                $filter = $filter_manager->createInstance('markdown', $config);
                return $filter->process($text, 'en');
            }
    }
    return NULL;
}
